# Generated by Django 4.2.4 on 2023-12-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='Song_Dur',
            field=models.CharField(max_length=101),
        ),
    ]
