# Generated by Django 4.2.4 on 2023-12-16 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_alter_songs_song_dur'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='unique_id',
            field=models.CharField(auto_created=True, default=uuid.UUID('3a0af70b-9c1a-11ee-94a7-107d1a2c293d'), max_length=2000),
        ),
        migrations.AlterField(
            model_name='songs',
            name='Song_Cover',
            field=models.ImageField(upload_to='media/songcovers'),
        ),
    ]
